services:
  backend:
    image: docker.entangled.ru/hgnd_v2/backend:latest
    ports:
      - ${BACKEND_PORT}:40080
    volumes:
      - ./volume:/volume
  frontend:
    image: docker.entangled.ru/hgnd_v2/frontend:latest
    ports:
      - "0.0.0.0:${FRONTEND_PORT}:80"